version: '3'

services:

    web:
        build:
            context: ./app
        command: gunicorn novas.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/novas/staticfiles
        expose:
        - 8000
        env_file:
        - .env
        depends_on:
            - db

    db:
        image: postgres:12
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/novas/staticfiles
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume: