version: '3'

services:

    web:
        build:
            context: ./app
        command: gunicorn novas.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/novas/staticfiles
        expose:
        - 8000
        env_file:
        - ./.env

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/novas/staticfiles
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    static_volume: