from .base import *

ALLOWED_HOSTS = []

CORS_ORIGIN_WHITELIST = ()

DEBUG = False
SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
